version: '3.8'

services:
  client:
    build: 
      context: ./client
      dockerfile: dockerfile
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./requirements.txt:/app/requirements.txt
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             python server.py"
