version: '3.8'

services:
  client:
    build: 
      context: ./client
      dockerfile: dockerfile
    ports:
      - "443:443"
    depends_on:
      - server
    networks:
      - app-network
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server/requirements.txt:/app/requirements.txt
    environment:
      - PORT=5000
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             python server.py"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
